//respuesta 'default' para testeo, habilitar o deshabilitar carga de datos desde éste archivo en views/EcommercePage/Sections/SectionProducts.js

export const responseJSON = {
  products: {
    "58448133": {
      vigencia_cotizacion: "01/02/2020",
      valor_asegurado: "15800000",
      dias_cotizados: "0",
      quotestage: "Created",
      cuotaInicialFinanciacion: "",
      valorCuotaFinanciacion: "",
      numeroCuotaFinanciacion: "",
      financiacionText: "",
      name: "Sura - Global",
      thumb:
        "http://app.agentemotor.com/components/com_aceshop/opencart/image/cache/data/sura-logo.jpg",
      price: "$2,158,000",
      manufacturer: "Sura",
      attribute: {
        "12": "$33",
        "14": "hijo",
        "20": "Sin Deducible",
        "21": "$3.040.000.000",
        "22": "$3.040.000.000",
        "23": "$3.040.000.000",
        "24": "$3.040.000.000",
        "25": "",
        "26": "Si",
        "28": "Cubrimiento al 100%",
        "29": "Deducible Unico : $987,000",
        "30": "Cubrimiento al 100%",
        "31": "Deducible Unico : $987,000",
        "33": "Deducible Unico : $987,000",
        "36": "Si",
        "37": "$80,000/DIA (PT) $0",
        "38": "reemplazo con kilometraje ilimitado. por 20 dias",
        "39": "reemplazo con kilometraje ilimitado. por 20 dias",
        "53": "Por deceso en accidente de tránsito",
        "54": "3 por vigencia",
        "55": "Si",
        "56": "Si, 12 por vigencia.",
        "57": "Por avería o accidente hasta 150 SMMLV",
        "60": "Transporte: $2.833.500 \r\nCustodia:$472.250\r\n",
        "64": "Si",
        "67":
          "Descuentos en la boutique, rotación de llantas, venta de baterías, entre otros</li></ul> Descuentos en Alineación y balanceo, mantenimiento preventivo básico, Peritaje comercial si vas a comprar o vender tu carro usado, un servicio gratuito y los tres siguientes con el 20% de descuento, durante la vigencia de la póliza</li></ul> Revisión preventiva antes de viaje: 3 gratuitas durante la vigencia</li></ul> Experto en mecánica para asesorarte en los problemas de tu vehículo: gratis e ilimitado</li></ul> Mantenimiento Autos SURA en nuestros Centros de Servicio, cotiza tu mantenimiento al #888 opción 2-2-1</li></ul> Acompañamiento a reclamaciones en el sitio del accidente o a domicilio</li></ul> Amparo de accidentes personales en accidentes de transito : $50,000,000 </li></ul> Asistencia Sura : Asistencia sura al producto </li></ul> Reemplazo de Llaves : Si pierdos o te hurtan tus llaves, SURA las reemplazara sin pago de deducible. </li></ul>",
        "85": "$387",
      },
    },
    "58448136": {
      vigencia_cotizacion: "01/02/2020",
      valor_asegurado: "15800000",
      dias_cotizados: "0",
      quotestage: "Created",
      cuotaInicialFinanciacion: "",
      valorCuotaFinanciacion: "",
      numeroCuotaFinanciacion: "",
      financiacionText: "",
      name: "Mapfre - Super Trebol",
      thumb:
        "http://app.agentemotor.com/components/com_aceshop/opencart/image/cache/data/mapfre-90x90.jpg",
      price: "$1,598,000",
      manufacturer: "Mapfre",
      attribute: {
        "12": "$313",
        "14": "hijo",
        "15": "",
        "19": "",
        "20": "Sin Deducible",
        "21": "$3.000.000.000",
        "22": "$3.000.000.000",
        "23": "$3.000.000.000",
        "24": "$3.000.000.000",
        "25": "",
        "26": "SI",
        "28": "Cubrimiento al 100%",
        "29": "Deducible Unico : $940,000",
        "30": "Cubrimiento al 100%",
        "31": "Deducible Unico : $940,000",
        "33": "Deducible Unico : $940,000",
        "36": "Si",
        "37": "1.5 SMDLV diario, hasta por 30 días",
        "38": "Si",
        "39": "Hasta por 10 días",
        "53": "Si",
        "55": "Si",
        "56": "10 CONDUCTORES POR VIGENCIA",
        "57": "Si",
        "64": "Si",
        "67":
          "Asistencia Mapfre</li></ul>\r\n Gastos exequiales : Gastos exequiales </li></ul>",
        "85": "$378",
      },
    },
    "58448137": {
      vigencia_cotizacion: "16/01/2020",
      valor_asegurado: "0",
      dias_cotizados: "0",
      quotestage: "Reject",
      cuotaInicialFinanciacion: "",
      valorCuotaFinanciacion: "",
      numeroCuotaFinanciacion: "",
      financiacionText: "",
      name: "Mapfre -Trebol",
      thumb:
        "http://app.agentemotor.com/components/com_aceshop/opencart/image/cache/data/mapfre-90x90.jpg",
      price: "$0",
      manufacturer: "Mapfre",
      attribute: {
        "12": "",
        "14": "padre",
        "15": "",
        "19": "",
        "20": "Sin Deducible",
        "21": "",
        "22": "",
        "23": "",
        "24": "",
        "25": "",
        "26": "Si",
        "28": "10%, minimo 1 SMMLV",
        "29": "10%, minimo 1 SMMLV",
        "30": "10%, minimo 1 SMMLV",
        "31": "10%, minimo 1 SMMLV",
        "33": "10%, minimo 1 SMMLV",
        "36": "Si",
        "37": "1.5 SMDLV diario, hasta por 30 días",
        "38": "Hasta por 15 días",
        "39": "Hasta por 7 días",
        "53": "Si",
        "55": "Si",
        "56": "10 CONDUCTORES POR VIGENCIA",
        "57": "Si",
        "64": "Si",
        "67": "Asistencia exequial</li></ul>\r\n",
        "85": "$378",
      },
    },
    "58448139": {
      vigencia_cotizacion: "16/02/2020",
      valor_asegurado: "15800000",
      dias_cotizados: "0",
      quotestage: "Created",
      cuotaInicialFinanciacion: "",
      valorCuotaFinanciacion: "",
      numeroCuotaFinanciacion: "",
      financiacionText: "",
      name: "Liberty - TotalCar",
      thumb:
        "http://app.agentemotor.com/components/com_aceshop/opencart/image/cache/data/liberty-logo160x90-90x90.jpg",
      price: "$1,469,000",
      manufacturer: "Liberty",
      attribute: {
        "12": "$37",
        "14": "hijo",
        "15": "",
        "19": "Livianos",
        "20": "Sin Deducible",
        "21": "$3.000.000.000",
        "22": "$1.000.000.000",
        "23": "$1.000.000.000",
        "24": "$2.000.000.000",
        "25": "",
        "26": "Penal: $13.385.074 / Civil: $6.770.660",
        "28": "Cubrimiento al 100%",
        "29": "10%, minimo 1 SMMLV",
        "30": "Cubrimiento al 100%",
        "31": "10%, minimo 1 SMMLV",
        "33": "10%, minimo 1 SMMLV",
        "36": "Si",
        "37": "$1.200.000",
        "38": "SI",
        "39": "SI",
        "53": "Por deceso en accidente de tránsito",
        "54": "2 por vigencia",
        "55": "Si",
        "56": "10 servicios por año",
        "57": "Por varada: 50 SMDLV, Por Accidente: 80 SMDLV",
        "60": "Transporte: $2.644.600 \r\nCustodia:$472.250",
        "64": "Si",
        "67":
          "Datos errados en la profesión del asegurado o en la placa (usados) puede generar cambios en el precio de la póliza </li></ul> Cobertura Asistencia al Hogar para emergencias con plomería, electricidad, cerrajería y vidrios rotos</li></ul> Sin clausula de permanencia</li></ul>\r\n Accidentes Personales</li></ul> Tramites De Transito </li></ul> Amparo de accidentes personales : 40000000 </li></ul> RC Familiar : 44000000 </li></ul> Gastos exequiales : Gastos exequiales </li></ul>",
        "85": "$383",
      },
    },
    "58448140": {
      vigencia_cotizacion: "01/02/2020",
      valor_asegurado: "15800000",
      dias_cotizados: "0",
      quotestage: "Created",
      cuotaInicialFinanciacion: "",
      valorCuotaFinanciacion: "",
      numeroCuotaFinanciacion: "",
      financiacionText: "",
      name: "HDI Formula Sicura",
      thumb:
        "http://app.agentemotor.com/components/com_aceshop/opencart/image/cache/data/logo-hdi-90x90.png",
      price: "$1,248,000",
      manufacturer: "HDI",
      attribute: {
        "12": "$304",
        "14": "hijo",
        "19": "Livianos",
        "20": "Sin Deducible",
        "21": "$4.000.000.000",
        "22": "$4.000.000.000",
        "23": "$4.000.000.000",
        "24": "$4.000.000.000",
        "25": "",
        "26": "Si",
        "28": "Cubrimiento al 100%",
        "29": "10%, minimo 1 SMMLV",
        "30": "Cubrimiento al 100%",
        "31": "10%, minimo 1 SMMLV",
        "33": "10%, minimo 1 SMMLV",
        "36": "Si",
        "37": "Sí. Hasta $1.562.484",
        "38": "Hasta 15 dias",
        "39": "Hasta 7 días",
        "53": "Opcional",
        "54": "Si",
        "55": "Si",
        "56": "Hasta 5 servicios por vigencia",
        "57": "Hasta 140 SMMDLV por evento",
        "60": "",
        "64": "Si",
        "67":
          "   Asistencia para el hogar </li> </ul>     Renta diaria hospitalización </li> </ul>     Asistencia Excequial</li> </ul>     Asistencia viaje seguro</li> </ul>     Asistencia llave perdida 1 SMMLV </li> </ul>     Chequeo vehiculo para viaje </li> </ul>     PequeÃ±os accesorios ( lunas de espejos, emblemas y boceles externos, brazos limpia brisas, tapa gasolina, pelÃ­cula de seguridad, copas de rin, manijas de puertas) 1 SMMLV (Pago de prima adicional)</li> </ul>   Llantas estalladas 1,5 SMMLV </li></ul>",
        "85": "$382",
      },
    },
    "58448143": {
      vigencia_cotizacion: "22/01/2020",
      valor_asegurado: "15800000",
      dias_cotizados: "0",
      quotestage: "Created",
      cuotaInicialFinanciacion: "",
      valorCuotaFinanciacion: "",
      numeroCuotaFinanciacion: "",
      financiacionText: "",
      name: "Estado - Familiar",
      thumb:
        "http://app.agentemotor.com/components/com_aceshop/opencart/image/cache/data/seguros-del-estado-90x90.jpg",
      price: "$1,168,000",
      manufacturer: "Estado",
      attribute: {
        "12": "$284",
        "14": "hijo",
        "15": "",
        "19": "",
        "20": "Sin Deducible",
        "21": "$1.500.000.000",
        "22": "$500.000.000",
        "23": "$500.000.000",
        "24": "$1.000.000.000",
        "25": "",
        "26": "SI",
        "28": "Cubrimiento al 100%",
        "29": "10%, minimo 1 SMMLV",
        "30": "Cubrimiento al 100%",
        "31": "10%, minimo 1 SMMLV",
        "33": "10%, minimo 1 SMMLV",
        "36": "Si",
        "37": "2 SMDLV* 30 DIAS",
        "38": "Vehiculo Remplazo Totales",
        "39": "SI",
        "53": "Sí. Cubierto bajo la cobertura de accidentes personales",
        "54": "No",
        "55": "Si",
        "56": "Si",
        "57": "SI",
        "60": "No",
        "64": "Si",
        "67":
          "Pequeños Accesorios cubre 1 SMMLV durante la vigencia</li></ul>\r\n Llantas Estalladas cubre 1 SMMLV durante la vigencia</li></ul>\r\n Llantas estalladas y pequeños accesorios(No aplica para PickUps)</li></ul>\r\n Carro especial de atención en caso de siniestro</li></ul>\r\n Orientación medica vía telefónica</li></ul> Vehículo de reemplazo aplica solo para las ciudades de Bogotá, Cali, Medellín, Barranquilla, Bucaramanga, Cartagena, Ibagué, Manizales y Pereira</li></ul>\r\n Orientación de guía médica y de droguerías, red con hasta el 50% dcto para médicos especialistas</li></ul>\r\n Asistencia FCI, ¡Personal experto y autorizado en recolección de pruebas en un accidente de tránsito si el caso lo amerita, facilitando la conciliación!</li></ul> Amparo de accidentes personales en accidentes de transito : (max. Cinco (5) personas) hasta 50000000 </li></ul>",
        "85": "$381",
      },
    },
    "58448145": {
      vigencia_cotizacion: "22/01/2020",
      valor_asegurado: "15800000",
      dias_cotizados: "366",
      quotestage: "Created",
      cuotaInicialFinanciacion: "",
      valorCuotaFinanciacion: "",
      numeroCuotaFinanciacion: "",
      financiacionText: "",
      name: "Equidad - Auto Plus",
      thumb:
        "http://app.agentemotor.com/components/com_aceshop/opencart/image/cache/data/descarga-90x90.jpg",
      price: "$1,039,000",
      manufacturer: "Equidad",
      attribute: {
        "12": "$896",
        "14": "hijo",
        "15": "",
        "19": "",
        "20": "Sin Deducible",
        "21": "$1.500.000.000",
        "22": "$500.000.000",
        "23": "$500.000.000",
        "24": "$1.000.000.000",
        "25": "",
        "26": "Si",
        "28": "Cubrimiento al 100%",
        "29": "10%, minimo 1 SMMLV",
        "30": "Cubrimiento al 100%",
        "31": "10%, minimo 1 SMMLV",
        "33": "10%, minimo 1 SMMLV",
        "36": "Si",
        "37": "20000 diarios, hasta por 30 Días",
        "38": "Hasta 15 días",
        "39": "Hasta 10 días. Aplica únicamente para casos de accidente.",
        "53": "",
        "54": "2 por vigencia",
        "55": "Si",
        "56":
          "Si, Limite 12 servicios durante la vigencia. Maximo 2 servicios mensuales",
        "57":
          "Si, hasta la ciudad de circulacion que registra, Max. por accidente hasta 100 SMDLV. por Varada hasta 60 SMDLV, por evento",
        "60": "Transporte: Si\r\nCustodia:$491.000",
        "64": "Si",
        "67":
          "Asistencia de asesor jurídico en accidente de tránsito.</li></ul>\r\n La revisión de viaje incluye el diagnóstico computarizado de los sistemas de alineación, suspensión y frenos. </li></ul>\r\n La cobertura de conductor elegido aplica para las ciudades de Bogotá, Medellín y Cali, Barranquilla, Santa Marta, Sincelejo, Cartagena, Montería, Cúcuta, La Dorada (Caldas), Manizales, Pereira, Armenia, Buenaventura, Buga, Palmira, Tuluá, Popayán, Pasto, Barbosa, Bucaramanga, Tunja, Villavicencio, Ibagué, Neiva y Girardot. </li></ul> </li></ul></li></ul> Asistencia Extendida Prima $32000 cobertura: Llantas estalladas, pequeños accesorios, viajes seguro, rotura de vidrio</li></ul> Opcional con Cobro de Prima Adicional:Cartera Protegida</li></ul>",
        "85": "$380",
      },
    },
    "58448146": {
      vigencia_cotizacion: "16/02/2020",
      valor_asegurado: "15800000",
      dias_cotizados: "365",
      quotestage: "Created",
      cuotaInicialFinanciacion: "",
      valorCuotaFinanciacion: "",
      numeroCuotaFinanciacion: "",
      financiacionText: "",
      name: "Axa Colpatria - Auto Plus",
      thumb:
        "http://app.agentemotor.com/components/com_aceshop/opencart/image/cache/data/colpatria-logo160x90-90x90.jpg",
      price: "$969,000",
      manufacturer: "Axa Colpatria",
      attribute: {
        "12": "$3.162",
        "14": "hijo",
        "20": "Sin Deducible",
        "21": "$3.000.000.000",
        "22": "$1.000.000.000",
        "23": "$1.000.000.000",
        "24": "$2.000.000.000",
        "26": "Si",
        "28": "Cubrimiento al 100%",
        "29": "Deducible Unico : $700,000",
        "30": "Cubrimiento al 100%",
        "31": "Deducible Unico : $700,000",
        "33": "Si",
        "36": "Si",
        "37": "$20.000Por día. \r\n60 días máximo\r\n",
        "38": "No_Cubre",
        "39": "Hasta 15 días, Solo si la reparación se estima en más de 6 días",
        "53":
          "Al asegurado y ocupantes en accidente de tránsito. hasta $2.266.800",
        "54": "2 por vigencia",
        "55": "Si",
        "56":
          "Si, en casco urbano de Bogota, Medellín, Cali, Cartagena y Bucaramanga\r\n\r\n",
        "57": "Hasta 320 Km.",
        "60": "",
        "64": "Si",
        "67":
          "Cobertura Llantas Estalladas Hasta por 1SMMLV</li></ul> Muerte accidente del conductor por : $50.000.000</li></ul> Prolongación a la vigencia de la póliza por el tiempo del vehículo en el taller de reparación</li></ul> Pago en sitio por daño a tercero</li></ul> Garantía en el tiempo de reparación (si el taller incumple en la fecha de entrega definida para la reparación del vehículo, se reconocerá el 50% del deducible a su cargo</li></ul> Acompañamiento de perito en sitio, en caso de accidente para las ciudades de Bogotá, Medellín, Cali, Pereira, Barranquilla y Bucaramanga.</li></ul> Cobertura Llantas Estalladas Hasta por 1SMMLV</li></ul> Asistencia para gastos de movilización ante pérdidas totales : 20.000 * 60 </li></ul>",
        "85": "$379",
      },
    },
    "58448148": {
      vigencia_cotizacion: "01/02/2020",
      valor_asegurado: "15800000",
      dias_cotizados: "365",
      quotestage: "Created",
      cuotaInicialFinanciacion: "",
      valorCuotaFinanciacion: "",
      numeroCuotaFinanciacion: "",
      financiacionText: "",
      name: "Bolivar - Vehiculos",
      thumb:
        "http://app.agentemotor.com/components/com_aceshop/opencart/image/cache/data/imagesBolivar-90x90.jpg",
      price: "$1,639,000",
      manufacturer: "Bolivar",
      attribute: {
        "12": "$48",
        "14": "hijo",
        "15": "",
        "19": "Livianos",
        "20": "Sin Deducible",
        "21": "$4.000.000.000",
        "22": "$4.000.000.000",
        "23": "$4.000.000.000",
        "24": "$4.000.000.000",
        "25": "",
        "26": "Si",
        "28": "10%, minimo 1 SMMLV",
        "29": "Deducible Unico : $800,000",
        "30": "10%, minimo 1 SMMLV",
        "31": "Deducible Unico : $800,000",
        "33": "Deducible Unico : $800,000",
        "36": "Si",
        "37": "1,5 SMDLV diario, hasta por 60 días",
        "38": "Hasta 30 días",
        "39": "Hasta 15 días",
        "53":
          "Sí. Cobertura de por muerte en accidente de tránsito por $5.000.000 por ocupante.",
        "54": "Si",
        "55": "Si",
        "56":
          "Cuenta con 4 servicios por mes, Solicítelo con 4 horas de anticipación",
        "57": "Hasta 50 SMDLV por evento",
        "60": "Transporte:$ 982.500\r\nCustodia: $589.500 ",
        "64": "Si",
        "67":
          "App de asistencia en tu Smartphone. </li></ul>\r\n Conciliación de lesiones y daños en el lugar del accidente.</li></ul>\r\n Conductor especial hasta 2 veces por mes</li></ul>\r\nPequeños Accesorios: Espejos, tapas, boceles, vidrios, llantas y emblemas, Hasta $1.100.000 Max. 2 por vigencia</li></ul> Llaves, Sin Limite Max. 2 vigencia</li></ul>\r\n Mensajeria Liviana Cuenta con dos servicios al mes y\r\ncubrimos 30 km a la redonda </li></ul>\r\n Valet parking para tus invitados, una vez poraño. </li></ul>\r\n Energía Segura: Cambio de batería a domicilio. </li></ul>\r\n No cubre asistencia en: Meta (Excepto Villavicencio), San Andrés, Amazonas, Choco, Vaupés, Guainía, Arauca, Casanare, Vichada, Putumayo, Guaviare, Caquetá. </li></ul> Pequeños accesorios : 1100000 </li></ul>",
        "85": "$377",
      },
    },
    "58448150": {
      vigencia_cotizacion: "16/01/2020",
      valor_asegurado: "0",
      dias_cotizados: "0",
      quotestage: "Fuera de politicas",
      cuotaInicialFinanciacion: "",
      valorCuotaFinanciacion: "",
      numeroCuotaFinanciacion: "",
      financiacionText: "",
      name: "Allianz - Liviano Particular",
      thumb:
        "http://app.agentemotor.com/components/com_aceshop/opencart/image/cache/data/allianz_logo160x90-90x90.jpg",
      price: "$0",
      manufacturer: "Allianz",
      attribute: {
        "12": "",
        "14": "Padre",
        "15": "",
        "19": "Livianos",
        "20": "Sin Deducible",
        "21": "$3.000.000.000",
        "22": "$3.000.000.000",
        "23": "$3.000.000.000",
        "24": "$3.000.000.000",
        "25": "",
        "26": "Si",
        "28": "Cubrimiento al 100%",
        "29": "Deducible Unico : $630,000",
        "30": "Cubrimiento al 100%",
        "31": "Deducible Unico : $630,000",
        "33": "Deducible Unico : $630,000",
        "36": "Si",
        "37": "Sí. Hasta $1.200.000",
        "38": "Si",
        "39": "Si",
        "53": "Por deceso en accidente de tránsito",
        "54": "1 por vigencia",
        "55": "Si",
        "56": "6 servicios por vigencia",
        "57":
          "Por varada: $950.000, Por Accidente: $1.300.000, Rescate $1.100.000. Hasta 3 servicios por vigencia",
        "60": "Transporte:$950.000\r\nCustodia: $190.000 \r\n\r\n\r\n",
        "64": "Si",
        "67":
          "Asistencia médica ambulatoria para asegurado, y cónyuge los 365 días del año, incluye entre otras, medico domiciliario y transporte en ambulancia gratuito caso de ser requerido</li></ul>\r\n Amparo de accidentes personales por accidente de tránsito $50.000.000</li></ul>\r\n En caso de pérdida total se ofrece tanto el vehículo de reemplazo como los gastos de movilización</li></ul>\r\n </ul> Sin clausula de permanencia</li></ul>\r\n",
        "85": "$376",
      },
    },
  },
  attribute_groups: {
    "8": {
      name: "Responsabilidad Civil Extracontractual",
      attribute_group_id: "8",
      attribute: {
        "20": {
          name: "Deducible ante pago de Responsabilidad Civil",
        },
        "21": {
          name: "Responsabilidad Civil Extracontractual (Limite Máximo)",
        },
        "22": {
          name: "Límite para daños a bienes de terceros ",
        },
        "23": {
          name: "Límite para lesiones o muerte a una persona",
        },
        "24": {
          name: "Límite para lesiones o muerte a dos o más personas",
        },
        "25": {
          name: "Responsabilidad civil en exceso",
        },
        "26": {
          name: "Asistencia jurídica procesos penales/civiles",
        },
      },
    },
    "9": {
      name:
        "Protección Ante Daños o Hurto Sobre el Valor Asegurado para el Momento de un Siniestro",
      attribute_group_id: "9",
      attribute: {
        "28": {
          name: "Deducible Pérdida Total Daños",
        },
        "29": {
          name: "Deducible Pérdida Parcial Daños",
        },
        "30": {
          name: "Deducible Pérdida Total Hurto",
        },
        "31": {
          name: "Deducible Pérdida Parcial Hurto",
        },
        "33": {
          name: "Eventos de la naturaleza como temblor, terremoto ",
        },
        "36": {
          name: "Amparo patrimonial",
        },
      },
    },
    "10": {
      name: "Garantías de Movilidad",
      attribute_group_id: "10",
      attribute: {
        "37": {
          name: "Asistencia para gastos de movilización ante pérdidas totales",
        },
        "38": {
          name: "Vehículo de reemplazo ante Perdidas Totales",
        },
        "39": {
          name: "Vehículo de reemplazo ante Perdidas Parciales",
        },
      },
    },
    "13": {
      name: "Asistencias en Viaje",
      attribute_group_id: "13",
      attribute: {
        "54": {
          name: "Revisión antes de viaje",
        },
        "55": {
          name:
            "Carro-Taller para despinchada, envío gasolina, cerrajería o batería",
        },
        "56": {
          name: "Conductor elegido",
        },
        "57": {
          name: "Servicio de Grúa ante accidente o varada*",
        },
        "60": {
          name: "Transporte o Custodia del Vehículo reparado o recuperado",
        },
        "64": {
          name:
            "Asesoria telefónica y/o en sitio de abogado en caso de accidente",
        },
      },
    },
    "15": {
      name: "Valores Agregados",
      attribute_group_id: "15",
      attribute: {
        "53": {
          name: "Gastos exequiales",
        },
        "67": {
          name: "Otros Valores Agregados",
        },
      },
    },
  },
  aseguradoInfo: {
    firstname: "Oscar Antonio",
    lastname: "TAMAYO RINCON",
    birthday: "1960-07-14",
    tipo_identificacion: "CC",
    estado_civil: "C",
    numero_documento: "6356571",
    genero: "M",
  },
  vehiculoInfo: {
    ciudad_circulacion_veh: "76001 - Cali - Valle del cauca",
    cf_veh_placa: "CQF188",
    cf_veh_0km: "No",
    cf_veh_modelo: "2008",
    cf_veh_fasecolda: "01601207",
    cf_veh_clase: "AUTOMOVIL",
    cf_veh_marca: "CHEVROLET",
    cf_veh_referencia: "OPTRA 1.6 L MT 1600CC AA",
    cf_veh_tipo_placa: "particular",
    cf_veh_tipo_uso: "particular",
    cf_veh_precio: "15800000",
    cf_veh_valor_accesorios: "0",
    cf_veh_tipo_alarma: "Alarma",
  },
  asesor_Info: {
    user_name: "asis_asesor3",
    first_name: "Yurani",
    last_name: "Ceballos Castro",
    title: "Asesor de Seguros",
    phone_work: "6625161",
    phone_mobile: "3185127910",
    email1: "soporte@grupoasistencia.com",
    address_street: "",
    address_city: "",
    address_state: "",
    vista_ofertas: "todos",
    tipo_usuario: "asesor",
  },
  agenciaInfo: {
    accountname: "grupoasistencia",
    email1: "grupoasistenciaagm@agentemotor.com",
    website: "www.grupoasistencia.com",
    cf_nombre: "Seguros Grupo Asistencia Ltda.",
    cf_logo:
      "/media/agencia/grupoasistencia/LOGO_FINAL_Artboard_3_copy_5__1_.png",
    bill_city: "Cali",
    bill_country: "Colombia",
    bill_state: "Valle del Cauca",
    bill_street: "Calle 70 No. 7T2 - 16",
  },
};
